// Auto-generated by `replay_log --emit-test`. Captured from a
// per-game JSONL log at turn 5 of game 1966633. Hand reconstruction is verified to match the logged STATE
// snapshot at the time of emission. Tweak the EXPECT_* asserts
// below to capture the desired regression.

#include <gtest/gtest.h>

#include "hanabi/basics/action.h"
#include "hanabi/basics/game.h"
#include "hanabi/basics/identity.h"
#include "hanabi/conventions/reactor0/decision.h"
#include "hanabi/logging/state_snapshot.h"
#include "replay_helpers.h"
#include "test_harness.h"

// Variant: Light-Pink-Fives & Orange (3 Suits). 3 players, our_player_index=1.

TEST(DecisionMaking1966633, T5LockedAliceGivesThePlayReveal) {
  // Reconstruct exactly the Game the live bot saw at turn 5.
  // The embedded JSON is the STATE record's `replay` section.
  const char* kSnapshotJson = R"json(
{
  "bot": "will-bot67",
  "ch": "STATE",
  "current_player_index": 1,
  "database_id": 1966633,
  "debug": {
    "cards_left": 13,
    "clue_tokens": 7,
    "current_player_index": 1,
    "discards": [
      {
        "order": 6,
        "rank": 3,
        "suit": 0
      }
    ],
    "endgame_turns": null,
    "hands": [
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              1
            ],
            "inferred": 32767,
            "info_lock": null,
            "order": 16,
            "possible": 32767,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              2
            ],
            "inferred": 32767,
            "info_lock": null,
            "order": 4,
            "possible": 32767,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              2
            ],
            "inferred": 32767,
            "info_lock": null,
            "order": 2,
            "possible": 32767,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              3
            ],
            "inferred": 32767,
            "info_lock": null,
            "order": 1,
            "possible": 32767,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              1
            ],
            "inferred": 32767,
            "info_lock": null,
            "order": 0,
            "possible": 32767,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot69",
        "player": 0
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 17407,
            "info_lock": null,
            "order": 15,
            "possible": 17407,
            "slot": 1,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 17407,
            "info_lock": null,
            "order": 9,
            "possible": 17407,
            "slot": 2,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": null,
            "inferred": 15360,
            "info_lock": null,
            "order": 8,
            "possible": 15360,
            "slot": 3,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 17407,
            "info_lock": null,
            "order": 7,
            "possible": 17407,
            "slot": 4,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 17407,
            "info_lock": null,
            "order": 5,
            "possible": 17407,
            "slot": 5,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot67",
        "player": 1
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              2
            ],
            "inferred": 14798,
            "info_lock": null,
            "order": 14,
            "possible": 14798,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              1
            ],
            "inferred": 1024,
            "info_lock": null,
            "order": 13,
            "possible": 17969,
            "slot": 2,
            "status": "CALLED_TO_DISCARD",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              1
            ],
            "inferred": 16912,
            "info_lock": null,
            "order": 12,
            "possible": 17969,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              1,
              1
            ],
            "inferred": 16912,
            "info_lock": null,
            "order": 11,
            "possible": 17969,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              0,
              5
            ],
            "inferred": 16912,
            "info_lock": null,
            "order": 10,
            "possible": 17969,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "yagami_black",
        "player": 2
      }
    ],
    "in_progress": true,
    "max_ranks": [
      5,
      5,
      5
    ],
    "move_history": [
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      }
    ],
    "play_stacks": [
      1,
      0,
      0
    ],
    "strikes": 0,
    "turn_count": 5,
    "waiting": []
  },
  "game_id": 24478,
  "replay": {
    "actions": [
      {
        "order": 0,
        "p": 0,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 1,
        "p": 0,
        "rank": 3,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 2,
        "p": 0,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 3,
        "p": 0,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 4,
        "p": 0,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 5,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 6,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 7,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 8,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 9,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 10,
        "p": 2,
        "rank": 5,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 11,
        "p": 2,
        "rank": 1,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 2,
        "suit": 1,
        "t": "draw"
      },
      {
        "giver": 0,
        "kind": "R",
        "list": [
          10,
          11,
          12,
          13
        ],
        "t": "clue",
        "target": 2,
        "value": 1
      },
      {
        "clues": 7,
        "max": 15,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 1,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 6,
        "p": 1,
        "rank": 3,
        "suit": 0,
        "t": "discard"
      },
      {
        "order": 15,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 8,
        "max": 15,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 2,
        "t": "turn"
      },
      {
        "giver": 2,
        "kind": "C",
        "list": [
          8
        ],
        "t": "clue",
        "target": 1,
        "value": 2
      },
      {
        "clues": 7,
        "max": 15,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 3,
        "t": "turn"
      },
      {
        "order": 3,
        "p": 0,
        "rank": 1,
        "suit": 0,
        "t": "play"
      },
      {
        "order": 16,
        "p": 0,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "clues": 7,
        "max": 15,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 4,
        "t": "turn"
      }
    ],
    "all_plays": false,
    "convention": "reactor0",
    "deck": [
      [
        0,
        1
      ],
      [
        2,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      null,
      [
        0,
        3
      ],
      null,
      null,
      null,
      [
        0,
        5
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      null,
      [
        2,
        1
      ]
    ],
    "names": [
      "will-bot69",
      "will-bot67",
      "yagami_black"
    ],
    "num_players": 3,
    "options": {
      "deck_plays": false,
      "detrimental_characters": false,
      "empty_clues": false,
      "num_players": 3,
      "one_extra_card": false,
      "one_less_card": false,
      "speedrun": false,
      "starting_player": 0,
      "variant_name": "Light-Pink-Fives & Orange (3 Suits)"
    },
    "our_player_index": 1,
    "rlocks": true,
    "variant": "Light-Pink-Fives & Orange (3 Suits)",
    "zcs_turn": -1
  },
  "ts": "2026-08-21T02:21:05.990",
  "turn": 5
}
  )json";
  auto rec = nlohmann::json::parse(kSnapshotJson);
  hanabi::Game game = hanabi::logging::apply_snapshot(rec);
  const hanabi::State& s = game.state;
  ASSERT_EQ(game.convention, hanabi::Convention::REACTOR0);

  const int us = s.our_player_index;
  const int bob = s.next_player_index(us);

  // The position. Alice is LOCKED -- every card chop-moved, so no chop to
  // discard -- and Bob holds a standing CTD, which is a safe discard and so
  // declines the whole of priority 3. At 7 clue tokens section 4 used to
  // decline too, leaving nothing but a bomb.
  EXPECT_TRUE(game.common.thinks_locked(game, us)) << "guard: Alice is locked";
  EXPECT_NE(s.clue_tokens, 8) << "guard: and NOT at 8 clues";
  EXPECT_FALSE(game.common.thinks_trash(game, bob).empty())
      << "guard: Bob has a safe discard, which is what declines priority 3";

  // Light-Pink-Fives & Orange: the 5s take every RANK clue but no COLOUR clue.
  // Bob's slot 4 is already clued down to {r1, r5, b1, b5, o1, o5}; Blue
  // touches the 1 and not the 5, pinning it to exactly Blue 1 on an empty
  // stack. That is a play REVEAL -- it stamps nothing -- and it is still a play
  // clue.
  const int blue = 1;
  ASSERT_EQ(s.play_stacks[blue], 0);
  hanabi::ClueAction blue_clue{us, bob,
                               s.clue_touched(s.hands[bob], hanabi::ClueKind::COLOUR, blue),
                               hanabi::BaseClue{hanabi::ClueKind::COLOUR, blue}};
  hanabi::Game hypo = game.simulate(hanabi::Action{blue_clue});
  auto reading = hanabi::reactor0::read_clue(game, hypo, blue_clue);
  EXPECT_EQ(reading.shape, hanabi::reactor0::ClueShape::STABLE_PLAY)
      << "a reveal that creates a play is a play clue, stamp or no stamp";
  ASSERT_GE(reading.stable_subject, 0);
  EXPECT_TRUE(hypo.common.thoughts[reading.stable_subject].inferred.is_exactly(
      hanabi::Identity{blue, 1}))
      << "and it pins the card to exactly Blue 1";

  // The outcome: give it, rather than bombing out of the locked hand.
  hanabi::PerformAction action = game.take_action();
  auto* colour = std::get_if<hanabi::PerformColour>(&action);
  ASSERT_NE(colour, nullptr) << "expected the Blue colour clue, not a bomb";
  EXPECT_EQ(colour->target, bob);
  EXPECT_EQ(colour->value, blue);
}
