// Auto-generated by `replay_log --emit-test`. Captured from a
// per-game JSONL log at turn 10 of game 1966091. Hand reconstruction is verified to match the logged STATE
// snapshot at the time of emission. Tweak the EXPECT_* asserts
// below to capture the desired regression.

#include <gtest/gtest.h>

#include "hanabi/basics/action.h"
#include "hanabi/basics/game.h"
#include "hanabi/basics/identity.h"
#include "hanabi/conventions/reactor0/decision.h"
#include "hanabi/conventions/reactor0/facts.h"
#include "hanabi/logging/state_snapshot.h"
#include "replay_helpers.h"
#include "test_harness.h"

// Variant: Rainbow-Ones & Orange (4 Suits). 3 players, our_player_index=0.

TEST(DecisionMaking1966091, T10ReactiveLockIsNotAnH4Clue) {
  // Reconstruct exactly the Game the live bot saw at turn 10.
  // The embedded JSON is the STATE record's `replay` section.
  const char* kSnapshotJson = R"json(
{
  "bot": "will-bot67",
  "ch": "STATE",
  "current_player_index": 0,
  "database_id": 1966091,
  "debug": {
    "cards_left": 20,
    "clue_tokens": 7,
    "current_player_index": 0,
    "discards": [
      {
        "order": 14,
        "rank": 1,
        "suit": 1
      },
      {
        "order": 6,
        "rank": 4,
        "suit": 2
      },
      {
        "order": 5,
        "rank": 1,
        "suit": 3
      }
    ],
    "endgame_turns": null,
    "hands": [
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1048575,
            "info_lock": null,
            "order": 16,
            "possible": 1048575,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1048575,
            "info_lock": null,
            "order": 4,
            "possible": 1048575,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1048575,
            "info_lock": null,
            "order": 3,
            "possible": 1048575,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1048575,
            "info_lock": null,
            "order": 2,
            "possible": 1048575,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 499183,
            "info_lock": null,
            "order": 0,
            "possible": 1048575,
            "slot": 5,
            "status": "CALLED_TO_DISCARD",
            "trash": false,
            "urgent": true
          }
        ],
        "name": "will-bot67",
        "player": 0
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              4
            ],
            "inferred": 984030,
            "info_lock": null,
            "order": 19,
            "possible": 984030,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              3
            ],
            "inferred": 918428,
            "info_lock": null,
            "order": 17,
            "possible": 918428,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              3,
              3
            ],
            "inferred": 131204,
            "info_lock": null,
            "order": 15,
            "possible": 131204,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": true,
            "id": [
              2,
              2
            ],
            "inferred": 2048,
            "info_lock": null,
            "order": 9,
            "possible": 2048,
            "slot": 4,
            "status": "CALLED_TO_PLAY",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              1,
              2
            ],
            "inferred": 65602,
            "info_lock": null,
            "order": 8,
            "possible": 65602,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "yagami_black",
        "player": 1
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              3,
              2
            ],
            "inferred": 1048575,
            "info_lock": null,
            "order": 18,
            "possible": 1048575,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              5
            ],
            "inferred": 1014720,
            "info_lock": null,
            "order": 13,
            "possible": 1014720,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              4
            ],
            "inferred": 1014720,
            "info_lock": null,
            "order": 12,
            "possible": 1014720,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              0,
              5
            ],
            "inferred": 30,
            "info_lock": null,
            "order": 11,
            "possible": 33855,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              0,
              3
            ],
            "inferred": 30,
            "info_lock": null,
            "order": 10,
            "possible": 33855,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot69",
        "player": 2
      }
    ],
    "in_progress": true,
    "max_ranks": [
      5,
      5,
      5,
      5
    ],
    "move_history": [
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Discard"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      }
    ],
    "play_stacks": [
      1,
      0,
      1,
      0
    ],
    "strikes": 0,
    "turn_count": 10,
    "waiting": [
      {
        "all_plays": false,
        "clue_kind": "C",
        "clue_value": 2,
        "focus_slot": 4,
        "giver": 2,
        "inverted": false,
        "react_order": 0,
        "reacter": 0,
        "receiver": 1,
        "receiver_hand": [
          19,
          17,
          15,
          9,
          8
        ],
        "rlocks": true,
        "turn": 9
      }
    ]
  },
  "game_id": 23824,
  "replay": {
    "actions": [
      {
        "order": 0,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 1,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 2,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 3,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 4,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 5,
        "p": 1,
        "rank": 1,
        "suit": 3,
        "t": "draw"
      },
      {
        "order": 6,
        "p": 1,
        "rank": 4,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 7,
        "p": 1,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 8,
        "p": 1,
        "rank": 2,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 9,
        "p": 1,
        "rank": 2,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 10,
        "p": 2,
        "rank": 3,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 11,
        "p": 2,
        "rank": 5,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 4,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 5,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 1,
        "suit": 1,
        "t": "draw"
      },
      {
        "giver": 0,
        "kind": "C",
        "list": [
          10,
          11,
          14
        ],
        "t": "clue",
        "target": 2,
        "value": 0
      },
      {
        "clues": 7,
        "max": 20,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 1,
        "t": "turn"
      },
      {
        "order": 5,
        "p": 1,
        "rank": 1,
        "suit": 3,
        "t": "play"
      },
      {
        "order": 15,
        "p": 1,
        "rank": 3,
        "suit": 3,
        "t": "draw"
      },
      {
        "clues": 8,
        "max": 20,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 2,
        "t": "turn"
      },
      {
        "giver": 2,
        "kind": "R",
        "list": [
          15
        ],
        "t": "clue",
        "target": 1,
        "value": 3
      },
      {
        "clues": 7,
        "max": 20,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 3,
        "t": "turn"
      },
      {
        "order": 1,
        "p": 0,
        "rank": 1,
        "suit": 2,
        "t": "play"
      },
      {
        "order": 16,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 7,
        "max": 20,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 4,
        "t": "turn"
      },
      {
        "order": 7,
        "p": 1,
        "rank": 1,
        "suit": 0,
        "t": "play"
      },
      {
        "order": 17,
        "p": 1,
        "rank": 3,
        "suit": 1,
        "t": "draw"
      },
      {
        "clues": 7,
        "max": 20,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 5,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 14,
        "p": 2,
        "rank": 1,
        "suit": 1,
        "t": "discard"
      },
      {
        "order": 18,
        "p": 2,
        "rank": 2,
        "suit": 3,
        "t": "draw"
      },
      {
        "clues": 8,
        "max": 20,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 6,
        "t": "turn"
      },
      {
        "giver": 0,
        "kind": "R",
        "list": [
          8,
          9
        ],
        "t": "clue",
        "target": 1,
        "value": 2
      },
      {
        "clues": 7,
        "max": 20,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 7,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 6,
        "p": 1,
        "rank": 4,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 19,
        "p": 1,
        "rank": 4,
        "suit": 1,
        "t": "draw"
      },
      {
        "clues": 8,
        "max": 20,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 8,
        "t": "turn"
      },
      {
        "giver": 2,
        "kind": "C",
        "list": [
          9
        ],
        "t": "clue",
        "target": 1,
        "value": 2
      },
      {
        "clues": 7,
        "max": 20,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 9,
        "t": "turn"
      }
    ],
    "all_plays": false,
    "convention": "reactor0",
    "deck": [
      null,
      [
        2,
        1
      ],
      null,
      null,
      null,
      [
        3,
        1
      ],
      [
        2,
        4
      ],
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        0,
        5
      ],
      [
        2,
        4
      ],
      [
        2,
        5
      ],
      [
        1,
        1
      ],
      [
        3,
        3
      ],
      null,
      [
        1,
        3
      ],
      [
        3,
        2
      ],
      [
        1,
        4
      ]
    ],
    "names": [
      "will-bot67",
      "yagami_black",
      "will-bot69"
    ],
    "num_players": 3,
    "options": {
      "deck_plays": false,
      "detrimental_characters": false,
      "empty_clues": false,
      "num_players": 3,
      "one_extra_card": false,
      "one_less_card": false,
      "speedrun": false,
      "starting_player": 0,
      "variant_name": "Rainbow-Ones & Orange (4 Suits)"
    },
    "our_player_index": 0,
    "rlocks": true,
    "variant": "Rainbow-Ones & Orange (4 Suits)",
    "zcs_turn": -1
  },
  "ts": "2026-08-20T17:08:37.462",
  "turn": 10
}
  )json";
  auto rec = nlohmann::json::parse(kSnapshotJson);
  hanabi::Game game = hanabi::logging::apply_snapshot(rec);
  const hanabi::State& s = game.state;

  ASSERT_EQ(game.convention, hanabi::Convention::REACTOR0);

  // The root cause, asserted directly. will-bot67 is the REACTER of a standing
  // waiting connection and holds the reacter-CTD it installed, so Precedence
  // step 2 says she actions it. Only an H4 clue may outrank that.
  const int us = s.our_player_index;
  ASSERT_FALSE(game.waiting.empty()) << "guard: a reaction is pending";
  EXPECT_EQ(game.waiting.front().reacter, us)
      << "we are the reacter, so the call on our hand is urgent";
  const int called = s.hands[us].back();  // slot 5, order 0
  ASSERT_EQ(game.meta[called].status, hanabi::CardStatus::CALLED_TO_DISCARD);
  ASSERT_TRUE(game.meta[called].urgent) << "guard: it is a REACTER call";

  // The bug: rank 2 to player 2 reads as a REACTIVE LOCK, and a lock stamps
  // CHOP_MOVED only a turn later. At clue time the receiver's predicted slot
  // therefore carries no status, which sailed past `clue_gets_finesse`'s
  // "stamped: Phase A, not B" test; the slot happened to hold a one-away card,
  // so the lock was classified H4. Because H4 outranks a pending reaction, the
  // bot abandoned its reaction to give it, and the game took a strike.
  {
    hanabi::ClueAction lock_clue{
        us, 2, s.clue_touched(s.hands[2], hanabi::ClueKind::RANK, 2),
        hanabi::BaseClue{hanabi::ClueKind::RANK, 2}};
    hanabi::Game hypo = game.simulate(hanabi::Action{lock_clue});
    EXPECT_EQ(hanabi::reactor0::read_clue(game, hypo, lock_clue).shape,
              hanabi::reactor0::ClueShape::REACTIVE_LOCK)
        << "guard: this candidate really is a lock, not a finesse";
    EXPECT_FALSE(hanabi::reactor0::clue_is_h4(game, hypo, lock_clue))
        << "a reactive lock is not a finesse, so it is not H4 and must not "
           "outrank the pending reaction";
  }

  // The symptom.
  hanabi::PerformAction action = game.take_action();
  auto* discard = std::get_if<hanabi::PerformDiscard>(&action);
  ASSERT_NE(discard, nullptr)
      << "the pending reaction is actioned, not abandoned for a clue";
  EXPECT_EQ(discard->target, called) << "and it is the reacter-CTD card";
}
