// Auto-generated by `replay_log --emit-test`. Captured from a
// per-game JSONL log at turn 10 of game 1966569. Hand reconstruction is verified to match the logged STATE
// snapshot at the time of emission. Tweak the EXPECT_* asserts
// below to capture the desired regression.

#include <gtest/gtest.h>

#include "hanabi/basics/action.h"
#include "hanabi/basics/game.h"
#include "hanabi/basics/identity.h"
#include "hanabi/conventions/reactor0/calls.h"
#include "hanabi/logging/state_snapshot.h"
#include "replay_helpers.h"
#include "test_harness.h"

// Variant: Muddy Rainbow & Orange (3 Suits). 3 players, our_player_index=0.

TEST(MiscReplay1966569, T10ChucksTheOrangeFourNotTheTrashOrange) {
  // Reconstruct exactly the Game the live bot saw at turn 10.
  // The embedded JSON is the STATE record's `replay` section.
  const char* kSnapshotJson = R"json(
{
  "bot": "will-bot67",
  "ch": "STATE",
  "current_player_index": 0,
  "database_id": 1966569,
  "debug": {
    "cards_left": 10,
    "clue_tokens": 5,
    "current_player_index": 0,
    "discards": [
      {
        "order": 4,
        "rank": 1,
        "suit": 0
      }
    ],
    "endgame_turns": null,
    "hands": [
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 25566,
            "info_lock": null,
            "order": 18,
            "possible": 31742,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 25564,
            "info_lock": null,
            "order": 16,
            "possible": 31742,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 14830,
            "info_lock": null,
            "order": 3,
            "possible": 31742,
            "slot": 3,
            "status": "CALLED_TO_DISCARD",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": null,
            "inferred": 1025,
            "info_lock": null,
            "order": 2,
            "possible": 1025,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 27614,
            "info_lock": null,
            "order": 1,
            "possible": 31742,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot67",
        "player": 0
      },
      {
        "cards": [
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              1
            ],
            "inferred": 1025,
            "info_lock": null,
            "order": 17,
            "possible": 1025,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              4
            ],
            "inferred": 28,
            "info_lock": null,
            "order": 15,
            "possible": 30,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              2
            ],
            "inferred": 25536,
            "info_lock": null,
            "order": 8,
            "possible": 31712,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              3
            ],
            "inferred": 4128,
            "info_lock": null,
            "order": 7,
            "possible": 31712,
            "slot": 4,
            "status": "CALLED_TO_DISCARD",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              3
            ],
            "inferred": 28,
            "info_lock": null,
            "order": 6,
            "possible": 30,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot69",
        "player": 1
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              5
            ],
            "inferred": 32767,
            "info_lock": null,
            "order": 19,
            "possible": 32767,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              2
            ],
            "inferred": 30,
            "info_lock": null,
            "order": 14,
            "possible": 31,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": true,
            "id": [
              0,
              1
            ],
            "inferred": 1,
            "info_lock": 1,
            "order": 13,
            "possible": 31,
            "slot": 3,
            "status": "CALLED_TO_PLAY",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              1,
              2
            ],
            "inferred": 32736,
            "info_lock": null,
            "order": 11,
            "possible": 32736,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              4
            ],
            "inferred": 31,
            "info_lock": null,
            "order": 10,
            "possible": 31,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "yagami_black",
        "player": 2
      }
    ],
    "in_progress": true,
    "max_ranks": [
      5,
      5,
      5
    ],
    "move_history": [
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      }
    ],
    "play_stacks": [
      1,
      0,
      3
    ],
    "strikes": 0,
    "turn_count": 10,
    "waiting": []
  },
  "game_id": 24404,
  "replay": {
    "actions": [
      {
        "order": 0,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 1,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 2,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 3,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 4,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 5,
        "p": 1,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 6,
        "p": 1,
        "rank": 3,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 7,
        "p": 1,
        "rank": 3,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 8,
        "p": 1,
        "rank": 2,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 9,
        "p": 1,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 10,
        "p": 2,
        "rank": 4,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 11,
        "p": 2,
        "rank": 2,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 3,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "giver": 0,
        "kind": "C",
        "list": [
          11,
          12
        ],
        "t": "clue",
        "target": 2,
        "value": 1
      },
      {
        "clues": 7,
        "max": 15,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 1,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 5,
        "p": 1,
        "rank": 1,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 15,
        "p": 1,
        "rank": 4,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 7,
        "max": 15,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 2,
        "t": "turn"
      },
      {
        "giver": 2,
        "kind": "C",
        "list": [
          7,
          8
        ],
        "t": "clue",
        "target": 1,
        "value": 1
      },
      {
        "clues": 6,
        "max": 15,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 3,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 0,
        "p": 0,
        "rank": 2,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 16,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 15,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 4,
        "t": "turn"
      },
      {
        "order": 9,
        "p": 1,
        "rank": 1,
        "suit": 0,
        "t": "play"
      },
      {
        "order": 17,
        "p": 1,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 15,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 5,
        "t": "turn"
      },
      {
        "giver": 2,
        "kind": "R",
        "list": [
          17
        ],
        "t": "clue",
        "target": 1,
        "value": 1
      },
      {
        "clues": 5,
        "max": 15,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 6,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 4,
        "p": 0,
        "rank": 1,
        "suit": 0,
        "t": "discard"
      },
      {
        "order": 18,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 15,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 7,
        "t": "turn"
      },
      {
        "giver": 1,
        "kind": "R",
        "list": [
          2
        ],
        "t": "clue",
        "target": 0,
        "value": 1
      },
      {
        "clues": 5,
        "max": 15,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 8,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 12,
        "p": 2,
        "rank": 3,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 19,
        "p": 2,
        "rank": 5,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 5,
        "max": 15,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 9,
        "t": "turn"
      }
    ],
    "all_plays": false,
    "convention": "reactor0",
    "deck": [
      [
        2,
        2
      ],
      null,
      null,
      null,
      [
        0,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        4
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        4
      ],
      null,
      [
        2,
        1
      ],
      null,
      [
        0,
        5
      ]
    ],
    "names": [
      "will-bot67",
      "will-bot69",
      "yagami_black"
    ],
    "num_players": 3,
    "options": {
      "deck_plays": false,
      "detrimental_characters": false,
      "empty_clues": false,
      "num_players": 3,
      "one_extra_card": false,
      "one_less_card": false,
      "speedrun": false,
      "starting_player": 0,
      "variant_name": "Muddy Rainbow & Orange (3 Suits)"
    },
    "our_player_index": 0,
    "rlocks": true,
    "variant": "Muddy Rainbow & Orange (3 Suits)",
    "zcs_turn": -1
  },
  "ts": "2026-08-21T01:11:25.241",
  "turn": 10
}
  )json";
  auto rec = nlohmann::json::parse(kSnapshotJson);
  hanabi::Game game = hanabi::logging::apply_snapshot(rec);
  const hanabi::State& s = game.state;
  ASSERT_EQ(game.convention, hanabi::Convention::REACTOR0);

  // Muddy Rainbow & Orange, stacks r1/m0/o3.
  const int orange = 2;
  ASSERT_TRUE(s.variant->suits[orange].suit_type.inverted);
  ASSERT_EQ(s.play_stacks[0], 1);
  ASSERT_EQ(s.play_stacks[orange], 3);

  const int us = s.our_player_index;

  // Slot 4 is the trap: {r1, o1}, BOTH trash, and all three r1 copies are
  // accounted for, so we know it is the o1. Chucking it is a play attempt on an
  // orange that is already past -- a strike. It must not be on the chuck list.
  const int trash_orange = s.hands[us][3];
  auto lists = hanabi::reactor0::action_lists(game, us);
  EXPECT_EQ(std::find(lists.chuck.begin(), lists.chuck.end(), trash_orange),
            lists.chuck.end())
      << "a trash card that could be orange is pitched, never chucked";

  // Slot 3 is the Orange 4, stamped CALLED_TO_DISCARD. The orange stack is at
  // 3, so chucking it puts it on the stack -- and the stamp is the instruction.
  const int called = s.hands[us][2];
  ASSERT_EQ(game.meta[called].status, hanabi::CardStatus::CALLED_TO_DISCARD);
  // We cannot read our own card's identity -- `deck[].id()` is nullopt for our
  // own hand, which is the whole point of the POV. What we CAN check is that
  // the reading still admits the Orange 4 (the replay's actual card) and that
  // the chuck is therefore sound.
  EXPECT_TRUE(game.common.thoughts[called].inferred.contains(
      hanabi::Identity{orange, 4}))
      << "guard: Orange 4 is still a live reading for the called card";
  EXPECT_TRUE(s.is_playable(hanabi::Identity{orange, 4}))
      << "guard: so chucking it advances the stack rather than striking";
  EXPECT_TRUE(hanabi::reactor0::call_is_actionable(game, us, called))
      << "nothing has made this call unchuckable";

  // The outcome: chuck the Orange 4. The bug chucked slot 4 instead and struck.
  hanabi::PerformAction action = game.take_action();
  auto* discard = std::get_if<hanabi::PerformDiscard>(&action);
  ASSERT_NE(discard, nullptr) << "Discard is the button that chucks";
  EXPECT_EQ(discard->target, called)
      << "chuck the called Orange 4 on slot 3, not the trash orange on slot 4";
  EXPECT_NE(discard->target, trash_orange);
}
