// Replay 1959065 turn 10 (reactor0, "Chimneys & Dark Orange (5 Suits)").
// bug_report_6_2_0.txt.
//
// Turn 5: will-bot69 clues Dark Orange to will-bot67, touching only order 3.
// The target is not the giver's Bob, so this is a REACTIVE clue with
// yagami_black as reacter, and the receiver's Dark Orange target is stamped
// CALLED_TO_DISCARD — on an inverted suit that is a CHUCK, i.e. a play call.
// Turn 6: the reacter plays, resolving the connection through
// `reactor0::react_play`'s COLOUR branch into `target_i_discard`.
//
// `target_i_discard` narrowed `inferred` to the NON-CRITICAL identities. Dark
// Orange is `oneOfEach`, so every identity is critical and the set emptied:
// the card was marked `meta.trash`, and `Game::elim`'s step-1 sweep then reset
// it to global empathy and cleared the status. The chuck signal was destroyed
// one turn after it was given, and order 3 — the playable Dark Orange 2 — was
// left neither playable (`order_playable` bails on `meta.trash`) nor
// discardable (`order_trash` bails on all-critical).
//
// The visible symptom is here at turn 10: will-bot67 discarded slot 1 instead
// of chucking slot 3.
//
// Snapshot auto-generated by `replay_log --emit-test`; asserts written by hand.
// Note `apply_snapshot` replays the full action list rather than restoring the
// logged meta, so this genuinely re-executes the turn-5 clue and the turn-6
// resolution.

#include <gtest/gtest.h>

#include "hanabi/basics/action.h"
#include "hanabi/basics/game.h"
#include "hanabi/basics/identity.h"
#include "hanabi/logging/state_snapshot.h"
#include "replay_helpers.h"
#include "test_harness.h"

// Variant: Chimneys & Dark Orange (5 Suits). 3 players, our_player_index=0.

TEST(MiscReplay1959065, OrangeChuckCallSurvivesResolution) {
  // Reconstruct exactly the Game the live bot saw at turn 10.
  // The embedded JSON is the STATE record's `replay` section.
  const char* kSnapshotJson = R"json(
{
  "bot": "will-bot67",
  "ch": "STATE",
  "current_player_index": 0,
  "database_id": 1959065,
  "debug": {
    "cards_left": 25,
    "clue_tokens": 5,
    "current_player_index": 0,
    "discards": [
      {
        "order": 17,
        "rank": 1,
        "suit": 2
      }
    ],
    "endgame_turns": null,
    "hands": [
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 998365,
            "info_lock": null,
            "order": 16,
            "possible": 1032191,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": null,
            "inferred": 28,
            "info_lock": null,
            "order": 4,
            "possible": 31,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": null,
            "inferred": 31457280,
            "info_lock": null,
            "order": 3,
            "possible": 31457280,
            "slot": 3,
            "status": "NONE",
            "trash": true,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": null,
            "inferred": 28,
            "info_lock": null,
            "order": 1,
            "possible": 31,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 998336,
            "info_lock": null,
            "order": 0,
            "possible": 1032160,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot67",
        "player": 0
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              3,
              3
            ],
            "inferred": 32489471,
            "info_lock": null,
            "order": 18,
            "possible": 32489471,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              2
            ],
            "inferred": 15172079,
            "info_lock": null,
            "order": 9,
            "possible": 15172079,
            "slot": 2,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              3,
              4
            ],
            "inferred": 15172079,
            "info_lock": null,
            "order": 7,
            "possible": 15172079,
            "slot": 3,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              5
            ],
            "inferred": 16384,
            "info_lock": null,
            "order": 6,
            "possible": 16384,
            "slot": 4,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": true,
            "id": [
              3,
              5
            ],
            "inferred": 17302032,
            "info_lock": null,
            "order": 5,
            "possible": 17302032,
            "slot": 5,
            "status": "CHOP_MOVED",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot69",
        "player": 1
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              2
            ],
            "inferred": 32489471,
            "info_lock": null,
            "order": 19,
            "possible": 32489471,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              3,
              2
            ],
            "inferred": 32489471,
            "info_lock": null,
            "order": 15,
            "possible": 32489471,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              4,
              3
            ],
            "inferred": 32489471,
            "info_lock": null,
            "order": 13,
            "possible": 32489471,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              3
            ],
            "inferred": 32489471,
            "info_lock": null,
            "order": 11,
            "possible": 32489471,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              4,
              5
            ],
            "inferred": 32489471,
            "info_lock": null,
            "order": 10,
            "possible": 32489471,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "yagami_black",
        "player": 2
      }
    ],
    "in_progress": true,
    "max_ranks": [
      5,
      5,
      5,
      5,
      5
    ],
    "move_history": [
      {
        "k": "clue",
        "v": "Lock"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Play"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "discard",
        "v": "None"
      }
    ],
    "play_stacks": [
      1,
      0,
      2,
      0,
      1
    ],
    "strikes": 0,
    "turn_count": 10,
    "waiting": []
  },
  "game_id": 15406,
  "replay": {
    "actions": [
      {
        "order": 0,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 1,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 2,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 3,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 4,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 5,
        "p": 1,
        "rank": 5,
        "suit": 3,
        "t": "draw"
      },
      {
        "order": 6,
        "p": 1,
        "rank": 5,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 7,
        "p": 1,
        "rank": 4,
        "suit": 3,
        "t": "draw"
      },
      {
        "order": 8,
        "p": 1,
        "rank": 2,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 9,
        "p": 1,
        "rank": 2,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 10,
        "p": 2,
        "rank": 5,
        "suit": 4,
        "t": "draw"
      },
      {
        "order": 11,
        "p": 2,
        "rank": 3,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 3,
        "suit": 4,
        "t": "draw"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "giver": 0,
        "kind": "R",
        "list": [
          5,
          6
        ],
        "t": "clue",
        "target": 1,
        "value": 5
      },
      {
        "clues": 7,
        "max": 25,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 1,
        "t": "turn"
      },
      {
        "giver": 1,
        "kind": "C",
        "list": [
          1,
          4
        ],
        "t": "clue",
        "target": 0,
        "value": 0
      },
      {
        "clues": 6,
        "max": 25,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 2,
        "t": "turn"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 1,
        "suit": 0,
        "t": "play"
      },
      {
        "order": 15,
        "p": 2,
        "rank": 2,
        "suit": 3,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 25,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 3,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 2,
        "p": 0,
        "rank": 1,
        "suit": 4,
        "t": "discard"
      },
      {
        "order": 16,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 25,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 4,
        "t": "turn"
      },
      {
        "giver": 1,
        "kind": "C",
        "list": [
          3
        ],
        "t": "clue",
        "target": 0,
        "value": 4
      },
      {
        "clues": 5,
        "max": 25,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 5,
        "t": "turn"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 1,
        "suit": 2,
        "t": "play"
      },
      {
        "order": 17,
        "p": 2,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "clues": 5,
        "max": 25,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 6,
        "t": "turn"
      },
      {
        "giver": 0,
        "kind": "C",
        "list": [
          6,
          8
        ],
        "t": "clue",
        "target": 1,
        "value": 2
      },
      {
        "clues": 4,
        "max": 25,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 7,
        "t": "turn"
      },
      {
        "order": 8,
        "p": 1,
        "rank": 2,
        "suit": 2,
        "t": "play"
      },
      {
        "order": 18,
        "p": 1,
        "rank": 3,
        "suit": 3,
        "t": "draw"
      },
      {
        "clues": 4,
        "max": 25,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 8,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 17,
        "p": 2,
        "rank": 1,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 19,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 5,
        "max": 25,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 9,
        "t": "turn"
      }
    ],
    "all_plays": false,
    "convention": "reactor0",
    "deck": [
      null,
      null,
      [
        4,
        1
      ],
      null,
      null,
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        4
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        4,
        5
      ],
      [
        1,
        3
      ],
      [
        0,
        1
      ],
      [
        4,
        3
      ],
      [
        2,
        1
      ],
      [
        3,
        2
      ],
      null,
      [
        2,
        1
      ],
      [
        3,
        3
      ],
      [
        0,
        2
      ]
    ],
    "names": [
      "will-bot67",
      "will-bot69",
      "yagami_black"
    ],
    "num_players": 3,
    "options": {
      "deck_plays": false,
      "detrimental_characters": false,
      "empty_clues": false,
      "num_players": 3,
      "one_extra_card": false,
      "one_less_card": false,
      "speedrun": false,
      "starting_player": 0,
      "variant_name": "Chimneys & Dark Orange (5 Suits)"
    },
    "our_player_index": 0,
    "rlocks": true,
    "variant": "Chimneys & Dark Orange (5 Suits)",
    "zcs_turn": -1
  },
  "ts": "2026-08-15T16:31:49.304",
  "turn": 10
}
  )json";
  auto rec = nlohmann::json::parse(kSnapshotJson);
  hanabi::Game game = hanabi::logging::apply_snapshot(rec);
  const hanabi::State& s = game.state;

  ASSERT_EQ(game.convention, hanabi::Convention::REACTOR0);

  const int us = 0;                 // will-bot67
  const int dark_orange = 4;
  ASSERT_TRUE(s.variant->suits[dark_orange].suit_type.inverted);
  ASSERT_TRUE(s.variant->suits[dark_orange].suit_type.dark)
      << "Dark Orange is oneOfEach, so every card of it is critical — that is "
         "what made the non-critical narrowing empty";
  ASSERT_EQ(s.play_stacks[dark_orange], 1)
      << "the stack is at 1, so Dark Orange 2 is exactly playable";

  const int chuck_order = s.hands[us][2];   // slot 3

  // The root cause, asserted directly: the call must still be standing, and
  // the card must not have been branded trash.
  EXPECT_EQ(game.meta[chuck_order].status, hanabi::CardStatus::CALLED_TO_DISCARD)
      << "the chuck call must survive the reacter's play";
  EXPECT_FALSE(game.meta[chuck_order].trash)
      << "a chuck is a play call — 'every identity is critical' is evidence "
         "the card is irreplaceable, not evidence it is trash";

  hanabi::PerformAction action = game.take_action();

  // The symptom.
  auto* discard = std::get_if<hanabi::PerformDiscard>(&action);
  ASSERT_NE(discard, nullptr)
      << "Discard is the button that chucks an orange onto its stack";
  EXPECT_EQ(discard->target, chuck_order)
      << "slot 3 is the called Dark Orange 2; discarding slot 1 was the bug";
}
