// Replay 1961419 turn 11 (reactor0, "Muddy Rainbow & Orange (3 Suits)").
//
// Stacks [2, 1, 2]. will-bot67's slot 4 was clued rank 4 and inferred exactly
// {Red 4, Orange 4} — its Muddy Rainbow 4 possibility was already eliminated by
// the two visible copies in will-bot69's hand. Orange is inverted, so pressing
// Discard on that card is a CHUCK: a play attempt onto an orange stack of 2.
// The bot pressed Discard and struck.
//
// Such a card has NO safe voluntary-discard button. Discard chucks it (Orange 4
// is two away); Play would be a genuine play attempt on the Red 4 possibility
// (also two away). Either button can only strike, so it must never be a discard
// candidate at all.
//
// It became one because `Player::discardable` admits a card when every
// possibility is *sieved* — covered elsewhere, so expendable
// (`player_game.cpp:286-290`). Both were: the other Red 4 sat in will-bot69's
// hand and the other Orange 4 in yagami_black's. That is a discard-PILE
// judgement and says nothing about which button is safe, and the orange-safety
// filter that exists for exactly this hazard was gated behind
// `m.order_trash(...)`, so it only ever guarded the empathy-trash candidates
// and never looked at this one.
//
// Note what the test does NOT assert: that the bot discards order 5, the card
// the rank-4 referential discard actually called to discard. It doesn't — it
// gives a lock clue instead, because a called discard scores exactly 0.0
// (`reactor/state_eval.cpp` folds CALLED_TO_DISCARD into `is_trash`) and any
// mildly positive clue clears that bar. That is a separate, pre-existing defect
// (TODO entry 18) and was already true before this fix, where only the buggy
// candidate's mispriced +0.5 beat the clue. The invariant worth pinning here is
// the safety one: neither button is ever pressed on order 8.
//
// Snapshot auto-generated by `replay_log --emit-test`; asserts written by hand.

#include <gtest/gtest.h>

#include <variant>

#include "hanabi/basics/action.h"
#include "hanabi/basics/game.h"
#include "hanabi/basics/identity.h"
#include "hanabi/logging/state_snapshot.h"
#include "replay_helpers.h"
#include "test_harness.h"

// Variant: Muddy Rainbow & Orange (3 Suits). 3 players, our_player_index=1.

TEST(MiscReplay1961419, SievedOrangeIsNotADiscardCandidate) {
  // Reconstruct exactly the Game the live bot saw at turn 11.
  // The embedded JSON is the STATE record's `replay` section.
  const char* kSnapshotJson = R"json(
{
  "bot": "will-bot67",
  "ch": "STATE",
  "current_player_index": 1,
  "database_id": 1961419,
  "debug": {
    "cards_left": 9,
    "clue_tokens": 5,
    "current_player_index": 1,
    "discards": [
      {
        "order": 14,
        "rank": 2,
        "suit": 0
      }
    ],
    "endgame_turns": null,
    "hands": [
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              1
            ],
            "inferred": 32749,
            "info_lock": null,
            "order": 20,
            "possible": 32749,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              1
            ],
            "inferred": 21376,
            "info_lock": null,
            "order": 4,
            "possible": 24549,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              2,
              4
            ],
            "inferred": 8200,
            "info_lock": null,
            "order": 2,
            "possible": 8200,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              2
            ],
            "inferred": 24481,
            "info_lock": null,
            "order": 1,
            "possible": 24549,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              3
            ],
            "inferred": 24549,
            "info_lock": null,
            "order": 0,
            "possible": 24549,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "yagami_black",
        "player": 0
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 24549,
            "info_lock": null,
            "order": 17,
            "possible": 24549,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 24549,
            "info_lock": null,
            "order": 15,
            "possible": 24549,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 24549,
            "info_lock": null,
            "order": 9,
            "possible": 24549,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": true,
            "id": null,
            "inferred": 8200,
            "info_lock": null,
            "order": 8,
            "possible": 8200,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 24549,
            "info_lock": null,
            "order": 5,
            "possible": 24549,
            "slot": 5,
            "status": "CALLED_TO_DISCARD",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot67",
        "player": 1
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              4
            ],
            "inferred": 32749,
            "info_lock": null,
            "order": 19,
            "possible": 32749,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              4
            ],
            "inferred": 32749,
            "info_lock": null,
            "order": 18,
            "possible": 32749,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              1,
              4
            ],
            "inferred": 972,
            "info_lock": null,
            "order": 13,
            "possible": 1005,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              0,
              5
            ],
            "inferred": 16,
            "info_lock": null,
            "order": 11,
            "possible": 16,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              3
            ],
            "inferred": 15360,
            "info_lock": null,
            "order": 10,
            "possible": 15360,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot69",
        "player": 2
      }
    ],
    "in_progress": true,
    "max_ranks": [
      5,
      5,
      5
    ],
    "move_history": [
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "play",
        "v": "None"
      },
      {
        "k": "clue",
        "v": "Discard"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "discard",
        "v": "None"
      },
      {
        "k": "discard",
        "v": "None"
      }
    ],
    "play_stacks": [
      2,
      1,
      2
    ],
    "strikes": 0,
    "turn_count": 11,
    "waiting": []
  },
  "game_id": 18185,
  "replay": {
    "actions": [
      {
        "order": 0,
        "p": 0,
        "rank": 3,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 1,
        "p": 0,
        "rank": 2,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 2,
        "p": 0,
        "rank": 4,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 3,
        "p": 0,
        "rank": 2,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 4,
        "p": 0,
        "rank": 1,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 5,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 6,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 7,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 8,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 9,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 10,
        "p": 2,
        "rank": 3,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 11,
        "p": 2,
        "rank": 5,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 4,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "giver": 0,
        "kind": "C",
        "list": [
          11,
          12,
          13,
          14
        ],
        "t": "clue",
        "target": 2,
        "value": 0
      },
      {
        "clues": 7,
        "max": 15,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 1,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 7,
        "p": 1,
        "rank": 1,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 15,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 7,
        "max": 15,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 2,
        "t": "turn"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 1,
        "suit": 0,
        "t": "play"
      },
      {
        "order": 16,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 7,
        "max": 15,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 3,
        "t": "turn"
      },
      {
        "giver": 0,
        "kind": "R",
        "list": [
          11
        ],
        "t": "clue",
        "target": 2,
        "value": 5
      },
      {
        "clues": 6,
        "max": 15,
        "score": 2,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 4,
        "t": "turn"
      },
      {
        "order": 6,
        "p": 1,
        "rank": 1,
        "suit": 1,
        "t": "play"
      },
      {
        "order": 17,
        "p": 1,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 15,
        "score": 3,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 5,
        "t": "turn"
      },
      {
        "order": 16,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "play"
      },
      {
        "order": 18,
        "p": 2,
        "rank": 4,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 15,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 6,
        "t": "turn"
      },
      {
        "giver": 0,
        "kind": "R",
        "list": [
          8
        ],
        "t": "clue",
        "target": 1,
        "value": 4
      },
      {
        "clues": 5,
        "max": 15,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 7,
        "t": "turn"
      },
      {
        "giver": 1,
        "kind": "R",
        "list": [
          2
        ],
        "t": "clue",
        "target": 0,
        "value": 4
      },
      {
        "clues": 4,
        "max": 15,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 8,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 14,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "discard"
      },
      {
        "order": 19,
        "p": 2,
        "rank": 4,
        "suit": 1,
        "t": "draw"
      },
      {
        "clues": 5,
        "max": 15,
        "score": 4,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 9,
        "t": "turn"
      },
      {
        "failed": false,
        "order": 3,
        "p": 0,
        "rank": 2,
        "suit": 2,
        "t": "discard"
      },
      {
        "order": 20,
        "p": 0,
        "rank": 1,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 5,
        "max": 15,
        "score": 5,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 10,
        "t": "turn"
      }
    ],
    "all_plays": false,
    "convention": "reactor0",
    "deck": [
      [
        0,
        3
      ],
      [
        2,
        2
      ],
      [
        2,
        4
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      null,
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      null,
      null,
      [
        2,
        3
      ],
      [
        0,
        5
      ],
      [
        0,
        1
      ],
      [
        1,
        4
      ],
      [
        0,
        2
      ],
      null,
      [
        0,
        2
      ],
      null,
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        1
      ]
    ],
    "names": [
      "yagami_black",
      "will-bot67",
      "will-bot69"
    ],
    "num_players": 3,
    "options": {
      "deck_plays": false,
      "detrimental_characters": false,
      "empty_clues": false,
      "num_players": 3,
      "one_extra_card": false,
      "one_less_card": false,
      "speedrun": false,
      "starting_player": 0,
      "variant_name": "Muddy Rainbow & Orange (3 Suits)"
    },
    "our_player_index": 1,
    "rlocks": true,
    "variant": "Muddy Rainbow & Orange (3 Suits)",
    "zcs_turn": -1
  },
  "ts": "2026-08-17T14:09:04.532",
  "turn": 11
}
  )json";
  auto rec = nlohmann::json::parse(kSnapshotJson);
  hanabi::Game game = hanabi::logging::apply_snapshot(rec);
  const hanabi::State& s = game.state;

  ASSERT_EQ(game.convention, hanabi::Convention::REACTOR0);

  const int us = 1;  // will-bot67
  const int red = 0;
  const int orange = 2;
  ASSERT_TRUE(s.variant->suits[orange].suit_type.inverted);
  ASSERT_FALSE(s.variant->suits[red].suit_type.inverted);

  // Slot 4: the clued rank 4, pinned to {Red 4, Orange 4} and nothing else.
  const int rank4_order = s.hands[us][3];
  const hanabi::Thought& t = game.me().thoughts[rank4_order];
  ASSERT_EQ(t.possible.length(), 2);
  ASSERT_TRUE(t.possible.contains(hanabi::Identity{red, 4}));
  ASSERT_TRUE(t.possible.contains(hanabi::Identity{orange, 4}));
  ASSERT_FALSE(t.id(/*infer=*/true).has_value())
      << "not pinned to one identity, so the pitch/chuck re-route in "
         "take_action's emission loop cannot fire";

  // Neither button is safe: each possibility is two away from its stack, so a
  // chuck strikes on the orange one and a play attempt strikes on the red one.
  ASSERT_EQ(s.play_stacks[orange], 2);
  ASSERT_EQ(s.play_stacks[red], 2);
  EXPECT_FALSE(s.is_playable(hanabi::Identity{orange, 4}));
  EXPECT_FALSE(s.is_playable(hanabi::Identity{red, 4}));

  // How it reached the discard pool, and why the old filter missed it: sieved,
  // not trash. If `is_sieved` behaviour ever shifts, this fails loudly and the
  // test stops silently proving nothing.
  EXPECT_NE(game.meta[rank4_order].status, hanabi::CardStatus::CALLED_TO_DISCARD);
  EXPECT_FALSE(game.me().order_trash(game, rank4_order))
      << "not empathy trash — which is exactly why the old, trash-gated "
         "orange-safety filter never examined it";
  auto discardable = game.me().discardable(game, us);
  EXPECT_NE(std::find(discardable.begin(), discardable.end(), rank4_order),
            discardable.end())
      << "still discardable() — the fix filters the candidate downstream "
         "rather than changing what `discardable` reports";

  hanabi::PerformAction action = game.take_action();

  // The invariant: whatever the bot decides to do, it does not press either
  // button on a card that has no safe button.
  auto* chuck = std::get_if<hanabi::PerformDiscard>(&action);
  EXPECT_FALSE(chuck != nullptr && chuck->target == rank4_order)
      << "pressing Discard chucks Orange 4 onto a stack of 2 — the strike this "
         "replay recorded";
  auto* play = std::get_if<hanabi::PerformPlay>(&action);
  EXPECT_FALSE(play != nullptr && play->target == rank4_order)
      << "pressing Play is no escape either: on the Red 4 possibility it is a "
         "real play attempt, two away from a red stack of 2";
}
