// Auto-generated by `replay_log --emit-test`. Captured from a
// per-game JSONL log at turn 4 of game 1967558. Hand reconstruction is verified to match the logged STATE
// snapshot at the time of emission. Tweak the EXPECT_* asserts
// below to capture the desired regression.

#include <gtest/gtest.h>

#include "hanabi/basics/action.h"
#include "hanabi/basics/game.h"
#include "hanabi/basics/identity.h"
#include "hanabi/logging/state_snapshot.h"
#include "replay_helpers.h"
#include <variant>

#include "test_harness.h"

// Variant: Odds and Evens & White (6 Suits). 3 players, our_player_index=0.

TEST(MiscReplay1967558, DroppedCallKeepsItsInference) {
  // Reconstruct exactly the Game the live bot saw at turn 4.
  // The embedded JSON is the STATE record's `replay` section.
  const char* kSnapshotJson = R"json(
{
  "bot": "will-bot67",
  "ch": "STATE",
  "current_player_index": 0,
  "database_id": 1967558,
  "debug": {
    "cards_left": 44,
    "clue_tokens": 6,
    "current_player_index": 0,
    "discards": [],
    "endgame_turns": null,
    "hands": [
      {
        "cards": [
          {
            "clued": false,
            "focused": true,
            "id": null,
            "inferred": 35684385,
            "info_lock": 35684385,
            "order": 4,
            "possible": 1073710079,
            "slot": 1,
            "status": "CALLED_TO_PLAY",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": null,
            "inferred": 31744,
            "info_lock": null,
            "order": 3,
            "possible": 31744,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1073710079,
            "info_lock": null,
            "order": 2,
            "possible": 1073710079,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1073710079,
            "info_lock": null,
            "order": 1,
            "possible": 1073710079,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": null,
            "inferred": 1073710079,
            "info_lock": null,
            "order": 0,
            "possible": 1073710079,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot67",
        "player": 0
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              5,
              5
            ],
            "inferred": 1041235967,
            "info_lock": null,
            "order": 9,
            "possible": 1041235967,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              2
            ],
            "inferred": 1041235967,
            "info_lock": null,
            "order": 8,
            "possible": 1041235967,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              2
            ],
            "inferred": 1041235967,
            "info_lock": null,
            "order": 7,
            "possible": 1041235967,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": true,
            "focused": false,
            "id": [
              4,
              1
            ],
            "inferred": 32505856,
            "info_lock": null,
            "order": 6,
            "possible": 32505856,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              1,
              1
            ],
            "inferred": 1041235967,
            "info_lock": null,
            "order": 5,
            "possible": 1041235967,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "yagami_black",
        "player": 1
      },
      {
        "cards": [
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              2
            ],
            "inferred": 1073741823,
            "info_lock": null,
            "order": 15,
            "possible": 1073741823,
            "slot": 1,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              2
            ],
            "inferred": 1073741823,
            "info_lock": null,
            "order": 14,
            "possible": 1073741823,
            "slot": 2,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              3,
              2
            ],
            "inferred": 1073741823,
            "info_lock": null,
            "order": 12,
            "possible": 1073741823,
            "slot": 3,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              2,
              2
            ],
            "inferred": 1073741823,
            "info_lock": null,
            "order": 11,
            "possible": 1073741823,
            "slot": 4,
            "status": "NONE",
            "trash": false,
            "urgent": false
          },
          {
            "clued": false,
            "focused": false,
            "id": [
              0,
              3
            ],
            "inferred": 1073741823,
            "info_lock": null,
            "order": 10,
            "possible": 1073741823,
            "slot": 5,
            "status": "NONE",
            "trash": false,
            "urgent": false
          }
        ],
        "name": "will-bot69",
        "player": 2
      }
    ],
    "in_progress": true,
    "max_ranks": [
      5,
      5,
      5,
      5,
      5,
      5
    ],
    "move_history": [
      {
        "k": "clue",
        "v": "Play"
      },
      {
        "k": "clue",
        "v": "Reactive"
      },
      {
        "k": "play",
        "v": "None"
      }
    ],
    "play_stacks": [
      0,
      0,
      0,
      0,
      1,
      0
    ],
    "strikes": 0,
    "turn_count": 4,
    "waiting": []
  },
  "game_id": 25633,
  "replay": {
    "actions": [
      {
        "order": 0,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 1,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 2,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 3,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 4,
        "p": 0,
        "rank": -1,
        "suit": -1,
        "t": "draw"
      },
      {
        "order": 5,
        "p": 1,
        "rank": 1,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 6,
        "p": 1,
        "rank": 1,
        "suit": 4,
        "t": "draw"
      },
      {
        "order": 7,
        "p": 1,
        "rank": 2,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 8,
        "p": 1,
        "rank": 2,
        "suit": 1,
        "t": "draw"
      },
      {
        "order": 9,
        "p": 1,
        "rank": 5,
        "suit": 5,
        "t": "draw"
      },
      {
        "order": 10,
        "p": 2,
        "rank": 3,
        "suit": 0,
        "t": "draw"
      },
      {
        "order": 11,
        "p": 2,
        "rank": 2,
        "suit": 2,
        "t": "draw"
      },
      {
        "order": 12,
        "p": 2,
        "rank": 2,
        "suit": 3,
        "t": "draw"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 1,
        "suit": 4,
        "t": "draw"
      },
      {
        "order": 14,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "giver": 0,
        "kind": "C",
        "list": [
          6
        ],
        "t": "clue",
        "target": 1,
        "value": 4
      },
      {
        "clues": 7,
        "max": 30,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 1,
        "num": 1,
        "t": "turn"
      },
      {
        "giver": 1,
        "kind": "C",
        "list": [
          3
        ],
        "t": "clue",
        "target": 0,
        "value": 2
      },
      {
        "clues": 6,
        "max": 30,
        "score": 0,
        "t": "status"
      },
      {
        "cpi": 2,
        "num": 2,
        "t": "turn"
      },
      {
        "order": 13,
        "p": 2,
        "rank": 1,
        "suit": 4,
        "t": "play"
      },
      {
        "order": 15,
        "p": 2,
        "rank": 2,
        "suit": 0,
        "t": "draw"
      },
      {
        "clues": 6,
        "max": 30,
        "score": 1,
        "t": "status"
      },
      {
        "cpi": 0,
        "num": 3,
        "t": "turn"
      }
    ],
    "all_plays": false,
    "convention": "reactor0",
    "deck": [
      null,
      null,
      null,
      null,
      null,
      [
        1,
        1
      ],
      [
        4,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        2
      ],
      [
        5,
        5
      ],
      [
        0,
        3
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        2
      ]
    ],
    "names": [
      "will-bot67",
      "yagami_black",
      "will-bot69"
    ],
    "num_players": 3,
    "options": {
      "deck_plays": false,
      "detrimental_characters": false,
      "empty_clues": false,
      "num_players": 3,
      "one_extra_card": false,
      "one_less_card": false,
      "speedrun": false,
      "starting_player": 0,
      "variant_name": "Odds and Evens & White (6 Suits)"
    },
    "our_player_index": 0,
    "rlocks": true,
    "variant": "Odds and Evens & White (6 Suits)",
    "zcs_turn": -1
  },
  "ts": "2026-08-21T19:19:12.518",
  "turn": 4
}
  )json";
  auto rec = nlohmann::json::parse(kSnapshotJson);
  hanabi::Game game = hanabi::logging::apply_snapshot(rec);
  const hanabi::State& s = game.state;
  ASSERT_EQ(game.convention, hanabi::Convention::REACTOR0);
  const int purple = 4;
  ASSERT_EQ(s.play_stacks[purple], 1) << "guard: will-bot69 played its p1 at T3";

  // yagami_black's slot 4. It was clued purple at T1 and stamped CALLED_TO_PLAY
  // with the inference {p1}; the other p1 then played, so rule 3 erased the dead
  // call. Under the static-inferred rule the SIGNAL goes and the INFERENCE
  // stays -- before v8.0.0 `erase_call` reverted it to all five purples.
  const int dead = s.hands[1][3];
  EXPECT_EQ(game.meta[dead].status, hanabi::CardStatus::NONE)
      << "the call is dead: p1 is on the stack, so pitching this copy does "
         "nothing";
  EXPECT_TRUE(game.common.thoughts[dead].inferred.is_exactly(
      hanabi::Identity{purple, 1}))
      << "but everyone still knows it is the duplicate p1";
  EXPECT_TRUE(game.common.thinks_trash(game, 1).size() > 0)
      << "which is what makes it a safe discard for yagami_black";

  // And that is what frees will-bot67 to take its own turn: priority 3 spends a
  // clue on Bob's chop only when Bob has no safe play or discard, and he has
  // one. T4 played `clue rank value=1 -> player 1` before v8.0.0.
  hanabi::PerformAction action = game.take_action();
  ASSERT_TRUE(std::holds_alternative<hanabi::PerformPlay>(action))
      << "will-bot67 should simply play its own reactive-CTP slot 1";
  EXPECT_EQ(std::get<hanabi::PerformPlay>(action).target, s.hands[0][0]);
}
